### ISSUE TITLE
Error on Purpur 1.19.3

### ISSUE THREAD

**Issue by editon96** [AlessioGr/NotQuests#175]
Hey I have Test you Plugin and it worked on 1.19.3 with an older version. 
But I want that you now that Version 5.9.1 and 5.10.0 dont work under 1.19.3 from Purpur Build 1876.

The Error there are printing are: https://mclo.gs/6GuCqxY

Thanks for you work and have a nice New Years Eve and Chrismas Time! :)

**Comment by editon96** [comment]
I am Blind that Happen because from the Intigration form Betong Quest seems to not be Uptodate...

**Comment by AlessioGr** [comment]
> I am Blind that Happen because from the Intigration form Betong Quest seems to not be Uptodate...

Yup exactly! You need to make sure you use a BetonQuest version which notquests supports - or just disable the betonquest integration in notquests config.

**Comment by editon96** [comment]
again the same...
Get that error I think the Beton Quest dude dont think about your nice Not Quest...

**Comment by editon96** [comment]
The Only difference are new Beton Quest new NotQuest and new Purpur.

**Comment by editon96** [comment]
https://pastebin.com/rYLV3sd5
If you want to watch inside that.
