### ISSUE TITLE
Action spawnmob not working 

### ISSUE THREAD

**Issue by HawtEboy** [AlessioGr/NotQuests#33]
Command /qa add action SpawnDrowned drowned 5 Location (world and coordinates)/Player location doesn't work. When it executes nothing happens. Other actions work I guess (had no problem with others for now).

I want to spawn them underwater if it changes something.

![image](https://user-images.githubusercontent.com/96828818/147668759-3075ee2d-34c9-4437-a059-1764724136ad.png)

Version: 1.18.1
PaperMC
Plugin ver. 3.2.2
No region with world guard.

**Comment by HawtEboy** [comment]
Trigger action SpawnMob while doing quest also doesn't work.

**Comment by AlessioGr** [comment]
@HawtEboy Thank you for reporting the bug! I have fixed it in v3.2.3: https://www.spigotmc.org/resources/95872/updates 😄
