### ISSUE TITLE
Using GUI in /quests sends random blank messages to chat

### ISSUE THREAD

**Issue by Dartanman** [AlessioGr/NotQuests#4]
Title says it all.

Steps to Reproduce:
- Do /quests
- Click any of the options
- Notice blank lines showing up in chat

Plugin Version: 1.6.2

**Comment by AlessioGr** [comment]
@Dartanman 

Fixed in v1.6.3: https://github.com/AlessioGr/NotQuests/releases/tag/v1.6.3
