### ISSUE TITLE
Objective Progress On Accepting Quest is not configurable

### ISSUE THREAD

**Issue by Dartanman** [AlessioGr/NotQuests#5]
Title says it all.

**Steps to Reproduce:**

- Do /quests
- Select "Take A Quest"
-  Choose a quest to begin
- See the message, particularly the OBJECTIVES section. Notice that only the header for this section is configurable.
- Ideally, the entire message would be configurable.

**Suggested Solution:**
Let the message(s) from QuestManager.sendActiveObjectivesAndProgress be configurable.

**Comment by AlessioGr** [comment]
@Dartanman 

Added in v1.6.4: https://github.com/AlessioGr/NotQuests/releases/tag/v1.6.4

with:
- https://github.com/AlessioGr/NotQuests/commit/2d6577bb7f07fab600849e655c5f404cc9242f5f
- https://github.com/AlessioGr/NotQuests/commit/5b4eb706a72604ecb686190c8dd89320af7ece50
