### ISSUE TITLE
CMI Support

### ISSUE THREAD

**Issue by Strahilchu** [AlessioGr/NotQuests#6]
This is a really cool plugin but I use CMI instead of EssentialsX

I think the only issue is how commands are executed since CMI has slightly different permission nodes.

For example "cmi.command.spawnmob" and there's "/money give" (instead of /eco give)

I think it would be simple to add CMI support, or a workaround would be okay too!

**Comment by AlessioGr** [comment]
Hey, I'm kinda confused at this. Where exactly would CMI support be needed? For what feature?

NotQuests doesn't have any special EssentialsX integration. You should be able to use NotQuests together with CMI without any issues

**Comment by AlessioGr** [comment]
Closing because of no reply
