### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by Foxiar** [AlessioGr/NotQuests#60]
Hello! I just translated NotQuests again on 4.10.1!
So I'm sending you a translated file
[cs-CZ.zip](https://github.com/AlessioGr/NotQuests/files/7963641/cs-CZ.zip)
If somebody finds out mistake, just contact me, I'll fix it.

**Comment by AlessioGr** [comment]
Hey, could you add the translations here: https://translate.notquests.com/notquests/cs ?

I'm not adding them directly via the language files anymore because sometimes it seems to confuse crowdin, and I'm scared to override other translations uploaded there
