### ISSUE TITLE
about EscortNPC

### ISSUE THREAD

**Issue by Lewis2333** [AlessioGr/NotQuests#61]
Hello, why do NPCS disappear when other players also start this quests? Is this a bug? Thanks for your reply!

**Comment by AlessioGr** [comment]
Hey, it currently just "re-uses" the one same NPC. That means it won't really work with multiple people taking that objective at the same time. I'm not quite happy with the current system as well.
It's already on my to-do list to add per-player npcs for that, or even an own npc system. I just didn't come to add it yet

**Comment by Lewis2333** [comment]
> Hey, it currently just "re-uses" the one same NPC. That means it won't really work with multiple people taking that objective at the same time. I'm not quite happy with the current system as well. It's already on my to-do list to add per-player npcs for that, or even an own npc system. I just didn't come to add it yet

Ok,Thank you <3
